In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df= pd.read_csv("train(new).csv")

In [2]:
df.head()

,id,Sex,Age,Height,Weight,Duration,Heart_Rate,Body_Temp,Calories,BMI,workout type
0,0,male,36,189.0,82,26,101.0,41.0,150.0,22.955684,HITT
1,1,female,64,163.0,60,8,85.0,39.7,34.0,22.582709,HITT
2,2,female,51,161.0,64,7,84.0,39.8,29.0,24.690405,HITT
3,3,male,20,192.0,90,25,105.0,40.7,140.0,24.414062,HITT
4,4,female,38,166.0,61,25,102.0,40.6,146.0,22.136740,HITT

In [3]:
df.tail()

,id,Sex,Age,Height,Weight,Duration,Heart_Rate,Body_Temp,Calories,BMI,workout type
208806,208806,male,30,182.0,82,17,97.0,40.3,81.0,24.755464,HITT
208807,208807,female,33,157.0,56,24,107.0,40.7,152.0,22.718974,HITT
208808,208808,female,20,166.0,68,22,106.0,40.8,129.0,24.677021,HITT
208809,208809,female,38,157.0,57,6,86.0,39.3,24.0,23.124670,HITT
208810,208810,female,74,159.0,57,25,103.0,40.0,NaN,NaN,NaN

In [4]:
df.describe()

,id,Age,Height,Weight,Duration,Heart_Rate,Body_Temp,Calories,BMI
count,208811.000000,208811.000000,208811.000000,208811.000000,208811.000000,208811.000000,208811.000000,208810.000000,208810.000000
mean,104405.000000,41.384913,174.693230,75.131449,15.411492,95.476292,40.035292,88.254791,24.371605
std,60278.687867,15.160565,12.842704,13.984040,8.362783,9.459924,0.780847,62.494694,1.513696
min,0.000000,20.000000,136.000000,37.000000,1.000000,67.000000,37.100000,1.000000,13.726443
25%,52202.500000,28.000000,164.000000,63.000000,8.000000,88.000000,39.600000,34.000000,23.255019
50%,104405.000000,40.000000,174.000000,74.000000,15.000000,95.000000,40.300000,76.000000,24.386526
75%,156607.500000,52.000000,185.000000,87.000000,23.000000,103.000000,40.700000,136.000000,25.479871
max,208810.000000,79.000000,222.000000,132.000000,30.000000,128.000000,41.500000,314.000000,46.443986

In [5]:
df.isnull().sum()

id              0
Sex             0
Age             0
Height          0
Weight          0
Duration        0
Heart_Rate      0
Body_Temp       0
Calories        1
BMI             1
workout type    1
dtype: int64

In [6]:
df['BMI'] = df['BMI'].fillna(df['BMI'].mean())
df['workout type'] = df['workout type'].fillna(df['workout type'].mode())
df['Calories'] = df['Calories'].fillna(df['Calories'].mean())


# Encode Sex column
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
df['workout type'] = df['workout type'].map({'HIIT': 0, 'Cardio': 1})

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.dtypes

id                int64
Sex               int64
Age               int64
Height          float64
Weight            int64
Duration          int64
Heart_Rate      float64
Body_Temp       float64
Calories        float64
BMI             float64
workout type    float64
dtype: object

In [10]:
x=df.drop("Calories", axis=1)
y=df["Calories"]

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [12]:
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor(
    n_estimators=150,
    max_depth=15,
    min_samples_split=6,
    random_state=42
)
model.fit(x_train,y_train)

RandomForestRegressor(max_depth=15, min_samples_split=6, n_estimators=150,
                      random_state=42)

In [13]:
y_pred = model.predict(x_test)

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2 Score:", r2_score(y_test, y_pred))

MAE: 2.363769264932671
MSE: 16.242862682296163
RMSE: 4.030243501613291
R2 Score: 0.9958008774078554

In [14]:
y_train_pred = model.predict(x_train)

from sklearn.metrics import r2_score
print("Train R2 Score:", r2_score(y_train, y_train_pred))
print("Test R2 Score:", r2_score(y_test, y_pred))

Train R2 Score: 0.9985640025955039
Test R2 Score: 0.9958008774078554

In [15]:
import pickle
pickle.dump(model,open('model.pkl','wb'))